### ISSUE TITLE
InitialIndex not work on SegmentTab position index but work in TabBarView

### ISSUE THREAD

**Issue by rizkijuliansyaham** [LanarsInc/animated-segmented-tab-control#15]
when I use the initialIndex, the TabBarView section positions the view as the initial index that I have specified, but for the position of the SegmentTab it is still at index 0, please advise.

**Comment by SviatManiuk** [comment]
Hi, thanks for your report!

Unfortunately, this is a bug. Fixed in version 1.1.0
