### ISSUE TITLE
SegmentedTabControl doesn't have isScrollable property?

### ISSUE THREAD

**Issue by kish-git** [LanarsInc/animated-segmented-tab-control#5]
Unlike the existing TabBar() widget that is made by the Flutter team, SegmentedTabControl() doesn't have isScrollable property.
as shown below,

TabBar(
isScrollable: true,
);

**Comment by SviatManiuk** [comment]
Hi!

The selected tab indicator is draggable, so the SegmentedTabControl cannot be scrollable.
