### ISSUE TITLE
BUG: AnimationController.stop() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by stormaref** [LanarsInc/animated-segmented-tab-control#8]
Hi 
Thanks for your beautiful package 
I use this component more than once and when I close a page with on of this and try to use this on another page this exception comes up
<img width="1440" alt="Screen Shot 1401-01-18 at 2 47 47 PM" src="https://user-images.githubusercontent.com/42512420/162177534-e8c22c21-7a1e-40a8-a265-1f32108621e2.png">

**Comment by CarloTerracciano** [comment]
any news?

**Comment by jawadabbasi923** [comment]
Same goes here. Any update ?

**Comment by stormaref** [comment]
> Same goes here. Any update ?

If you implement it in the right way you wouldn't face this issue anymore
I changed the way I use it
If you couldn't understand how to make it work leave a comment and I'll share my code

**Comment by jawadabbasi923** [comment]
> > Same goes here. Any update ?
> 
> If you implement it in the right way you wouldn't face this issue anymore I changed the way I use it If you couldn't understand how to make it work leave a comment and I'll share my code

Please let me know your solution

**Comment by ondev** [comment]
use DefaultTabController instead of TabController

**Comment by ChabeletsV** [comment]
@stormaref Hello, have the same bug. Show me your code please

**Comment by stormaref** [comment]
> @stormaref Hello, have the same bug. Show me your code please

Hi
Sorry it's been a long time and I cannot even remember the project in which I used this :)
